### PR TITLE
Ported to Core22

### PR DESCRIPTION
**Pull request by soumyaDghosh**
I have a plan to rebase the snap, but for now, porting to core22

### CODE REVIEW

**Comment by fcastilloec** [comment]
Thanks for contributing with this PR, but I will hold off on merging this. `core18` is still supported and a valid choice when building. There's no need to upgrade unless it's fixing a bug or introducing a feature. I haven't seen any deprecation notices for `core18`, so until then, we'll leave this PR pending.

**Comment by soumyaDghosh** [comment]
No, let me explain you. Core18 is the snap based on the Ubuntu 18.04 and core20= Ubuntu 20.04, core22=Ubuntu 22.04. core18 and 20 should only be used when core22 is just failing. Every snap should be upgraded to the latest core possible. This introduces latest packages, which introduces bug fixes and everything. Also, as most of the snaps now have core22, core18 will just take extra space in the users pc. Like, in my pc, only headset uses core18. With headset updated to core22, this can improve the stability and the overall performance also. With the latest refreshments brought to snaps.

**Comment by fcastilloec** [comment]
I'm well aware of how snap `cores` work and what they're based on. Bug fixes and updates are still available for `core18`. We probably release a new version almost every month only for snaps because of this.
I get that if we were just starting to develop a snap, we'll probably be using `core22`. It's bad practice to start with an old base, but our app has been around for a while (we actually started with `core16` before it was even named that) and there's really no need to update (yet). The only compelling reason I see is saving space on your drive, but this is only the case if we're the only app using `core18` and this might not be true for all users. I have multiple applications installed and dependent on `core18`, `core20`, and `core22`. In addition, disk space is no longer an issue nowadays.

Ubuntu 18.04, and hence `core18`, might become deprecated sometime later this year. When that date comes, will revisit this PR.

**Comment by soumyaDghosh** [comment]
No latest gnome and gtk based apps use `core18`, every big apps like `vlc`, `firefox`, `krita` shifted to `core20` and `core22` far ago. To be honest, in my snap list the only snap that uses core18 is headset. And this is true for many. Also, I don't see any harm in being updated. As it'll also boost the performance of the app itself. I was also working on the `npm` plugin to use here. But, it'll take time. If that's used, this app can be easily built from source.

**Comment by soumyaDghosh** [comment]
Hii @fcastilloec I have also added support for symbolic icons in this PR. Users after logging out once after installation, will be able to see the icons properly

**Pull request closed without merging**
